### ISSUE TITLE
适配Android 10问题

### ISSUE THREAD

**Issue by zhyhub** [entronad/flutter_echarts#145]
在Android 10 及以上 报错闪退 Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference

**Comment by leononly** [comment]
I am facing this issue too 
`2022-03-17 13:23:58.131 14094-14094/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zeoniqgo, PID: 14094
    java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
        at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1668)
        at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1909)
        at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1220)
        at io.flutter.plugins.webviewflutter.c2$a.run(Unknown Source:42)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)`

**Comment by gaoshan85** [comment]
I am facing this issue too.
After I upgraded webview_flutter to the latest 3.0.2, I ran the demo, and no exception was reported when I clicked. However, the graph cannot be displayed anymore.

**Comment by beboprich** [comment]
Same issue here, after push a new window with some graphs

**Comment by entronad** [comment]
Please try v2.4.0
