### ISSUE TITLE
Recently change error, Come from javaScript resource.Please solve it in original resource.Thanks.

### ISSUE THREAD

**Issue by Onperson** [entronad/flutter_echarts#189]
Unhandled Exception: PlatformException(FWFEvaluateJavaScriptError, Failed evaluating JavaScript., A JavaScript exception occurred (WKErrorDomain:4:{WKJavaScriptExceptionLineNumber: Unsupported Type: 45, WKJavaScriptExceptionMessage: TypeError: null is not an object (evaluating 't.getAttribute'), WKJavaScriptExceptionSourceURL: Unsupported Type: about:blank, NSLocalizedDescription: A JavaScript exception occurred, WKJavaScriptExceptionColumnNumber: Unsupported Type: 218226}), null)
#0      WKWebViewHostApiImpl.evaluateJavaScriptForInstances (package:webview_flutter_wkwebview/src/web_kit/web_kit_api_impls.dart:1061:7)
<asynchronous suspension>
#1      WebKitWebViewController.runJavaScript (package:webview_flutter_wkwebview/src/webkit_webview_controller.dart:401:7)
<asynchronous suspension>
#2      _EchartsState.init (package:flutter_echarts/flutter_echarts.dart:99:5)
<asynchronous suspension>

**Comment by morozovilya-coder163** [comment]
Good afternoon
did you manage to solve this?

**Comment by huangbos** [comment]
我通过以下方式解决了此问题:
1.数据必须非null,
2.设置echarts reloadAfterInit:false

**Comment by huangbos** [comment]
I resolved this issue through the following methods:

1. The data must be non null,

2. Set echarts reloadAfterInit to false
