### ISSUE TITLE
Exception: Trying to create an already created platform view

### ISSUE THREAD

**Issue by blackredscarf** [entronad/flutter_echarts#25]
Probably throws this error:
```
E/flutter (32506): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create an already created platform view, view id: 0
E/flutter (32506): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:85)
E/flutter (32506): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/flutter (32506): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (32506): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter (32506): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter (32506): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter (32506): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (32506): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/flutter (32506): 	at android.os.Looper.loop(Looper.java:173)
E/flutter (32506): 	at android.app.ActivityThread.main(ActivityThread.java:8147)
E/flutter (32506): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (32506): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/flutter (32506): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by entronad** [comment]
I sometimes  met with this, and solved it by restart the debug.

**Comment by shenhuaxiyuan** [comment]
I get this error too. When I switch UI too frequently with tabs， this error occured.

**Comment by entronad** [comment]
@shenhuaxiyuan 

This seems caused by some native mechanism, which can not be solved by dart code.
I suggest to add a debounce function to you tabs to prevent switching too fast
